#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Catelog.API/Catelog.API.csproj", "Catelog.API/"]
COPY ["Catelog.Core/Catelog.Core.csproj", "Catelog.Core/"]
COPY ["Catelog.Infrastructure/Catelog.Infrastructure.csproj", "Catelog.Infrastructure/"]
COPY ["Catelog.Application/Catelog.Application.csproj", "Catelog.Application/"]
RUN dotnet restore "Catelog.API/Catelog.API.csproj"
COPY . .
WORKDIR "/src/Catelog.API"
RUN dotnet build "Catelog.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Catelog.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Catelog.API.dll"]